    [package]
name = "my-test"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15"
noise = "0.9"
rayon = "1.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
